export const testContacts = [
  {
    valid: true,
    firstName: "Arun",
    lastName: "Kumar",
    email: "arun@example.com",
    phoneNumber: "9876543210",
    address: "12 Gandhi Street",
    city: "Chennai",
    state: "Tamil Nadu",
    country: "India",
    postalCode: "600001",
  },
  {
    valid: false,
    firstName: "",
    lastName: "Kumar",
    email: "arun@example.com",
    phoneNumber: "9876543210",
    address: "12 Gandhi Street",
    city: "Chennai",
    state: "Tamil Nadu",
    country: "India",
    postalCode: "600001",
    expectedError: /first name must be at least/i,
  },
  {
    valid: false,
    firstName: "Priya",
    lastName: "Ramesh",
    email: "priya-at-example.com",
    phoneNumber: "9123456780",
    address: "45 Anna Nagar",
    city: "Coimbatore",
    state: "Tamil Nadu",
    country: "India",
    postalCode: "641001",
    expectedError: /invalid email address/i,
  },
];
